### ISSUE TITLE
Getting Stack Traces in Logs from Azure Persistence Failures

### ISSUE THREAD

**Issue by littleAndroidMan** [petabridge/Akka.Persistence.Azure#350]
Something new that has come up is that I am now seeing azure persistence plugin stack traces in the console when loading an element from blob storage unsuccessfully. I don't know if this error is a misconfiguration on my end or normal azure log spam:

```
[ERROR][10/24/2023 17:33:17.452Z][Thread 0146][akka.tcp://myActorSystem@myActorSystem-0.myActorSystem:9223/system/sharding/sessions/10/mysession-dffffd5a-2917-4286-8650-e6d2e028dbd8] Persistence failure when replaying events for persistenceId [mysession-dffffd5a-2917-4286-8650-e6d2e028dbd8]. Last known sequence number [0]
Cause: Azure.RequestFailedException: The specified blob does not exist.
RequestId:<guid>
Time:2023-10-24T17:33:17.4521243Z
Status: 404 (The specified blob does not exist.)
ErrorCode: BlobNotFound
Headers:
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: <guid>
x-ms-client-request-id: <guid>
x-ms-version: 2021-12-02
x-ms-error-code: BlobNotFound
Date: Tue, 24 Oct 2023 17:33:17 GMT
Content-Length: 215
Content-Type: application/xml
at Azure.Storage.Blobs.BlobRestClient.DownloadAsync(String snapshot, String versionId, Nullable`1 timeout, String range, String leaseId, Nullable`1 rangeGetContentMD5, Nullable`1 rangeGetContentCRC64, String encryptionKey, String encryptionKeySha256, Nullable`1 encryptionAlgorithm, Nullable`1 ifModifiedSince, Nullable`1 ifUnmodifiedSince, String ifMatch, String ifNoneMatch, String ifTags, CancellationToken cancellationToken)
at Azure.Storage.Blobs.Specialized.BlobBaseClient.StartDownloadAsync(HttpRange range, BlobRequestConditions conditions, DownloadTransferValidationOptions validationOptions, Int64 startOffset, Boolean async, CancellationToken cancellationToken)
at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadStreamingInternal(HttpRange range, BlobRequestConditions conditions, DownloadTransferValidationOptions transferValidationOverride, IProgress`1 progressHandler, String operationName, Boolean async, CancellationToken cancellationToken)
at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadStreamingDirect(HttpRange range, BlobRequestConditions conditions, DownloadTransferValidationOptions transferValidationOverride, IProgress`1 progressHandler, String operationName, Boolean async, CancellationToken cancellationToken)
at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadInternal(HttpRange range, BlobRequestConditions conditions, Boolean rangeGetContentHash, Boolean async, CancellationToken cancellationToken)
at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadAsync(HttpRange range, BlobRequestConditions conditions, Boolean rangeGetContentHash, CancellationToken cancellationToken)
at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadAsync(CancellationToken cancellationToken)
at Akka.Persistence.Azure.Snapshot.AzureBlobSnapshotStore.LoadAsync(String persistenceId, SnapshotSelectionCriteria criteria)
at Akka.Util.Internal.AtomicState.CallThrough[T](Func`1 task)
at Akka.Util.Internal.AtomicState.CallThrough[T](Func`1 task)
```

**Comment by Arkatufus** [comment]
@littleAndroidMan which Akka.Persistence.Azure version are you using?

**Comment by Aaronontheweb** [comment]
1.5.1 - I added that to the support ticket @Arkatufus

**Comment by Arkatufus** [comment]
@littleAndroidMan how often does this happen?
The only possibility that I can think of is when 2 persistent actors were using the same persistence id and one actor is trying to recover while the other deleted the snapshot.

**Comment by littleAndroidMan** [comment]
@Arkatufus It appears very frequently in the logs. We're running it on a 4 pod AKS cluster at the moment, and this error appeared with our latest test deploy to the cluster.

**Comment by Aaronontheweb** [comment]
Issue was on the user's end - multiple clusters all talking to the same storage account.
