### ISSUE TITLE
PersistentIds with "/" and ShardCoordinator

### ISSUE THREAD

**Issue by motmot80** [petabridge/Akka.Persistence.Azure#98]
Hello,

Azure table storage does not support "/" (slash) as a partition key.
Activating the journal within a sample sharding cluster results in errors concerning this restriction.

For example the akka.net build in shard coordinator uses his path as persistence id:

| Propery  | Value |
|----------|:-------------:|
| PartitionKey |  "/system/sharding/areaCoordinator/singleton/coordinator" |
| RowKey | "0000000000000000001" |
| SeqNo | 1 | 

Resulting in:

```
Cause: Microsoft.WindowsAzure.Storage.StorageException: Element 0 in the batch returned an unexpected response code.
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteAsyncInternal[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token) in C:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\WindowsRuntime\Core\Executor\Executor.cs:line 316
   at Akka.Persistence.Azure.Journal.AzureTableStorageJournal.WriteMessagesAsync(IEnumerable`1 atomicWrites)
Request Information
RequestID:f7cdc5bd-b002-0003-2d3a-47f6f2000000
RequestDate:Sat, 20 Jun 2020 19:40:07 GMT
StatusMessage:0:Bad Request - Error in query syntax.
ErrorCode:
ErrorMessage:0:Bad Request - Error in query syntax.
```

You should find a way to escape these characters to support any kind of persistence id.

Thanks in advance and best regards
Thomas

**Comment by motmot80** [comment]
I quick fixed it by changing "/" to "-"... working like a charm.
